name: push to hub docker
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Get push tag
        id: slug
        run: |
          echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: watsy0007/stealth:${{ steps.slug.outputs.tag }}

